AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  sentimentanalysis:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 384
      Timeout: 63
      Role: 'arn:aws:iam::528902077445:role/sentiment_analysis_tailored-role'
      Layers:
        - 'arn:aws:lambda:us-east-1:528902077445:layer:nltk:3'
        - >-
          arn:aws:lambda:us-east-1:528902077445:layer:NaiveBayesClassifierTrainedModelDOTpickle:1
