AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  DynamoDBwriter:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 384
      Timeout: 61
      Role: >-
        arn:aws:iam::528902077445:role/service-role/DynamoDB_writer-role-l2q9bh9b
